insert into INGREDIENT_META (PRESERVATION_DATE, INGREDIENT_META_ID, NAME) values (3, 1, '사과');
insert into INGREDIENT_META (PRESERVATION_DATE, INGREDIENT_META_ID, NAME) values (6, 2, '배');
insert into INGREDIENT_META (PRESERVATION_DATE, INGREDIENT_META_ID, NAME) values (9, 3, '바나나');
insert into USERS (USER_ID, DEVICE_TOKEN) values (1, '123');
insert into REFRIGERATOR (REFRIGERATOR_ID, USER_ID, NAME) values (1, 1, '냉장고');
insert into INGREDIENT (END_DATE, INGREDIENT_ID, INGREDIENT_META_ID, PURCHASE_DATE, REFRIGERATOR_ID) values (null, 1, 1, timestamp('2023-07-14 23:59:59'), 1);
insert into INGREDIENT (END_DATE, INGREDIENT_ID, INGREDIENT_META_ID, PURCHASE_DATE, REFRIGERATOR_ID) values (null, 2, 2, timestamp('2023-07-14 23:59:59'), 1);
insert into INGREDIENT (END_DATE, INGREDIENT_ID, INGREDIENT_META_ID, PURCHASE_DATE, REFRIGERATOR_ID) values (null, 3, 3, timestamp('2023-07-14 23:59:59'), 1);
