name: CICD

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: 저장소 checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ZERO_SECRET }}
          submodules: true

        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
        
      - name: 도커 이미지 빌드
        run: docker build -t kodongcheon/v1 .
    
      - name: Docker Hub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker Hub 퍼블리시
        run: docker push kodongcheon/v1
      
      - name: aws 접속 및 docker image 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PEM_KEY }}
          script: |
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker pull kodongcheon/v1
            docker run -d -p 8080:8080 --name app kodongcheon/v1
